# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  run_tests:
    working_directory: ~/espnet_onnx
    docker:
      - image: circleci/python:3.8
    environment:
      PYTHONPATH: ~/s3prl
      
    steps:
      - checkout
      - run: sudo apt-get -y update; sudo apt-get install libsndfile1
      - restore_cache: # restore s3prl folder
          key: s3prl
      - run: bash /home/circleci/espnet_onnx/tools/ci_test.sh
      - save_cache:
          key: s3prl
          paths:
            - ~/s3prl
            - ~/.cache/s3prl

workflows:
  build_and_test:
    jobs:
      - run_tests
